from __future__ import annotations

from typing import Any

def default_runtime_profile() -> dict[str, Any]:
    return {
        "id": "runtime-profile-default",
        "name": "默认 V1 流程",
        "enabled_steps": [
            "ingestion",
            "cleaning",
            "normalization",
            "tokenization",
            "dictionary_application",
            "filtering",
            "analysis",
            "export",
        ],
        "cleaning": {
            "strip_html": True,
            "strip_urls": True,
            "strip_email": False,
            "strip_phone": False,
            "normalize_whitespace": True,
            "normalize_punctuation": True,
            "full_half_width_normalize": True,
            "lowercase_english": True,
            "remove_emoji": False,
            "remove_special_chars": False,
        },
        "normalization": {
            "convert_traditional_to_simplified": False,
            "normalize_numbers": False,
            "normalize_time_expr": False,
            "apply_regex_rules": True,
            "regex_rule_priority": "rule_order",
        },
        "tokenization": {
            "language_mode": "mixed",
            "tokenizer_backend": "default",
            "use_custom_lexicon": True,
            "use_phrase_lexicon": True,
            "preserve_domain_phrases": True,
            "split_hyphenated_terms": True,
            "split_slash_terms": False,
            "normalize_camel_case": True,
            "keep_original_order": True,
            "min_token_length_before_filter": 1,
            "enable_ngrams": False,
            "ngram_min": 2,
            "ngram_max": 2,
        },
        "dictionary": {
            "apply_standard_terms": True,
            "apply_synonym_map": True,
            "apply_near_synonym_map": True,
            "apply_stopwords": True,
            "apply_exclusion_terms": True,
            "conflict_resolution": "priority",
        },
        "filtering": {
            "min_token_length": 2,
            "filter_numeric_tokens": False,
            "min_term_frequency": 1,
            "filter_by_pos": False,
            "keep_single_char_important_terms": True,
        },
        "analysis": {
            "top_n": 200,
            "cooccurrence_window": 5,
            "min_cooccurrence": 2,
            "feature_term_count": 1000,
            "top_k_per_doc": 10,
            "top_k_project": 100,
            "similarity_method": "cosine",
            "min_similarity": 0.2,
            "similarity_top_k": 200,
            "topic_algorithm": "nmf",
            "topic_model_k": 4,
            "keyword_cluster_k": 4,
            "document_cluster_k": 4,
            "include_frequency_statistics": True,
            "include_term_document_relations": True,
            "include_term_year_relations": True,
            "include_cooccurrence_analysis": True,
            "include_similarity_analysis": True,
            "include_feature_term_selection": True,
            "include_keyword_extraction": True,
            "include_keyword_clustering": True,
            "include_institution_keyword_analysis": True,
            "include_institution_topic_analysis": True,
            "include_document_clustering": True,
        },
        "export": {
            "export_csv": True,
            "export_xlsx": True,
            "export_png": True,
            "export_html_report": True,
            "include_audit": True,
            "chart_dpi": 320,
            "watermark_enabled": False,
            "watermark_text": "TextFlow Studio",
        },
        "nodes": [],
        "edges": [],
        "node_configs": {},
        "execution_order": [
            "ingestion",
            "cleaning",
            "normalization",
            "tokenization",
            "dictionary_application",
            "filtering",
            "analysis",
            "export",
        ],
        "run_scope": {
            "mode": "all_documents",
            "source_values": [],
            "institution_values": [],
            "category_values": [],
            "year_from": None,
            "year_to": None,
            "selected_doc_ids": [],
        },
        "recipe_id": "standard_analysis",
        "output_bundle_id": "full_report",
    }
